name: build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Build and push DSS gpu
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile-gpu
          platforms: linux/amd64
          push: true
          tags: ejtraderlabs/dss:gpu
      -
        name: Build and push DSS cpu
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile-cpu
          platforms: linux/amd64
          push: true
          tags: ejtraderlabs/dss:cpu
